service: twopass
frameworkVersion: '2'

provider:
  name: aws
  runtime: go1.x
  memorySize: 128
  timeout: 5
  lambdaHashingVersion: 20201221

  stage: dev
  region: us-east-1

  apiGateway:
    apiKeys:
      - twopassTestKey
    usagePlan:
      throttle:
        burstLimit: 5
        rateLimit: 3

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:DeleteItem
        - dynamodb:UpdateItem
      Resource: !GetAtt SecretsTable.Arn

  environment:
    SECRETSTABLE: !Ref SecretsTable

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  createsecret:
    handler: bin/createsecret
    events:
      - http:
          path: /createsecret
          method: post
          private: true
  getsecret:
    handler: bin/getsecret
    events:
      - http:
          path: /getsecret
          method: post
          private: true
  updatesecret:
    handler: bin/updatesecret
    events:
      - http:
          path: /updatesecret
          method: put
          private: true
  deletesecret:
    handler: bin/deletesecret
    events:
      - http:
          path: /deletesecret
          method: post
          private: true

resources:
  Resources:
    SecretsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-secretstable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH